//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/InputSettings/MyControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

    public partial class @CustomInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }

        public @CustomInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyControlls"",
    ""maps"": [
        {
            ""name"": ""SpaceShip_AM"",
            ""id"": ""199a8f50-3475-426f-8fd5-477cee88ab9f"",
            ""actions"": [
                {
                    ""name"": ""ButtonExample"",
                    ""type"": ""Button"",
                    ""id"": ""efa8e514-aaf3-4bc5-9663-1c36e09a88c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ValueAction"",
                    ""type"": ""Value"",
                    ""id"": ""84eedff8-04e6-41aa-8d42-7ff2c3554ead"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""28f02469-7181-4166-baeb-d51812cb3825"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""62830220-74f8-4c60-9079-26329591340f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""52fd4587-d1da-4abc-ad42-6248cee21532"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonExample"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a57787a6-a6f6-4cec-ab1a-019b96cb1eb8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonExample"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39e12140-ddd5-46be-b75a-05da2886c779"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonExample"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a984fa3-125b-47a4-8917-634556a6b1bd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonExample"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""83a0fc8c-a5b6-4c00-9cd0-d2a6942a7d54"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ValueAction"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""08b28d4e-a000-4300-895d-a8666bd13acd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ValueAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7fa2884b-c2af-48ed-9855-74d287ec51bf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ValueAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""86ca960b-dee6-486e-ac38-42e0facf500e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ValueAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""39c0c98c-a891-40b9-8804-61c357bf9fc7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ValueAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fd16a3eb-3f97-4039-b629-baa69d8c2913"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ValueAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3a65f36b-cd49-4efb-b544-4bebbd815d0c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e3080d4c-9647-4db7-a90e-289ee276173e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""eccf4062-dd9c-4ad2-92a2-7bd05b0bf3e7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ce13894b-b488-4b9b-90f7-f7579853f06d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aabbd38a-edef-46b1-8fb0-2278526cfeec"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d5f72f41-22f6-45e7-b58e-f382f9d8667f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // SpaceShip_AM
            m_SpaceShip_AM = asset.FindActionMap("SpaceShip_AM", throwIfNotFound: true);
            m_SpaceShip_AM_ButtonExample = m_SpaceShip_AM.FindAction("ButtonExample", throwIfNotFound: true);
            m_SpaceShip_AM_ValueAction = m_SpaceShip_AM.FindAction("ValueAction", throwIfNotFound: true);
            m_SpaceShip_AM_Move = m_SpaceShip_AM.FindAction("Move", throwIfNotFound: true);
            m_SpaceShip_AM_Rotate = m_SpaceShip_AM.FindAction("Rotate", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // SpaceShip_AM
        private readonly InputActionMap m_SpaceShip_AM;
        private ISpaceShip_AMActions m_SpaceShip_AMActionsCallbackInterface;
        private readonly InputAction m_SpaceShip_AM_ButtonExample;
        private readonly InputAction m_SpaceShip_AM_ValueAction;
        private readonly InputAction m_SpaceShip_AM_Move;
        private readonly InputAction m_SpaceShip_AM_Rotate;

        public struct SpaceShip_AMActions
        {
            private @CustomInput m_Wrapper;

            public SpaceShip_AMActions(@CustomInput wrapper)
            {
                m_Wrapper = wrapper;
            }

            public InputAction @ButtonExample => m_Wrapper.m_SpaceShip_AM_ButtonExample;
            public InputAction @ValueAction => m_Wrapper.m_SpaceShip_AM_ValueAction;
            public InputAction @Move => m_Wrapper.m_SpaceShip_AM_Move;
            public InputAction @Rotate => m_Wrapper.m_SpaceShip_AM_Rotate;

            public InputActionMap Get()
            {
                return m_Wrapper.m_SpaceShip_AM;
            }

            public void Enable()
            {
                Get().Enable();
            }

            public void Disable()
            {
                Get().Disable();
            }

            public bool enabled => Get().enabled;

            public static implicit operator InputActionMap(SpaceShip_AMActions set)
            {
                return set.Get();
            }

            public void SetCallbacks(ISpaceShip_AMActions instance)
            {
                if (m_Wrapper.m_SpaceShip_AMActionsCallbackInterface != null)
                {
                    @ButtonExample.started -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnButtonExample;
                    @ButtonExample.performed -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnButtonExample;
                    @ButtonExample.canceled -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnButtonExample;
                    @ValueAction.started -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnValueAction;
                    @ValueAction.performed -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnValueAction;
                    @ValueAction.canceled -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnValueAction;
                    @Move.started -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnMove;
                    @Rotate.started -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnRotate;
                    @Rotate.performed -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnRotate;
                    @Rotate.canceled -= m_Wrapper.m_SpaceShip_AMActionsCallbackInterface.OnRotate;
                }

                m_Wrapper.m_SpaceShip_AMActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ButtonExample.started += instance.OnButtonExample;
                    @ButtonExample.performed += instance.OnButtonExample;
                    @ButtonExample.canceled += instance.OnButtonExample;
                    @ValueAction.started += instance.OnValueAction;
                    @ValueAction.performed += instance.OnValueAction;
                    @ValueAction.canceled += instance.OnValueAction;
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Rotate.started += instance.OnRotate;
                    @Rotate.performed += instance.OnRotate;
                    @Rotate.canceled += instance.OnRotate;
                }
            }
        }

        public SpaceShip_AMActions @SpaceShip_AM => new SpaceShip_AMActions(this);

        public interface ISpaceShip_AMActions
        {
            void OnButtonExample(InputAction.CallbackContext context);
            void OnValueAction(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
        }
    }
